In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x=torch.FloatTensor(3,4,5)
x

tensor([[[ 2.1019e-44,  0.0000e+00, -4.4592e-28,  7.5390e-43, -9.8289e-30],
         [ 7.5390e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00, -4.4598e-28,  7.5390e-43, -2.8950e+26],
         [-4.0576e+29,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00]],

        [[ 2.9423e+26,  1.7699e+31,  7.7447e+31,  8.7654e-39,  0.0000e+00],
         [ 0.0000e+00,  2.1019e-44,  0.0000e+00,  1.4013e-45,  0.0000e+00],
         [ 1.7753e+28,  3.0452e+32,  1.6664e+35,  1.0510e-43,  0.0000e+00],
         [ 0.0000e+00,  2.1019e-44,  0.0000e+00,  1.7615e+19,  4.5559e-41]],

        [[-9.8160e-30,  7.5390e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00, -4.4598e-28,  7.5390e-43],
         [ 1.4956e+14,  3.9960e+02,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00,  6.7421e+22,  1.6630e+22, -6.3293e-30,  7.5390e-43]]])

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x.view(6,10)

tensor([[ 2.1019e-44,  0.0000e+00, -4.4592e-28,  7.5390e-43, -9.8289e-30,
          7.5390e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00, -4.4598e-28,  7.5390e-43, -2.8950e+26,
         -4.0576e+29,  0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
        [ 2.9423e+26,  1.7699e+31,  7.7447e+31,  8.7654e-39,  0.0000e+00,
          0.0000e+00,  2.1019e-44,  0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.7753e+28,  3.0452e+32,  1.6664e+35,  1.0510e-43,  0.0000e+00,
          0.0000e+00,  2.1019e-44,  0.0000e+00,  1.7615e+19,  4.5559e-41],
        [-9.8160e-30,  7.5390e-43,  0.0000e+00,  0.0000e+00,  2.1019e-44,
          0.0000e+00,  1.4013e-45,  0.0000e+00, -4.4598e-28,  7.5390e-43],
        [ 1.4956e+14,  3.9960e+02,  0.0000e+00,  0.0000e+00,  2.1019e-44,
          0.0000e+00,  6.7421e+22,  1.6630e+22, -6.3293e-30,  7.5390e-43]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x*torch.Tensor([1,4,2,2,1])

tensor([[[ 2.1019e-44,  0.0000e+00, -8.9183e-28,  1.5078e-42, -9.8289e-30],
         [ 7.5390e-43,  0.0000e+00,  0.0000e+00,  4.2039e-44,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00, -8.9196e-28,  1.5078e-42, -2.8950e+26],
         [-4.0576e+29,  0.0000e+00,  0.0000e+00,  4.2039e-44,  0.0000e+00]],

        [[ 2.9423e+26,  7.0796e+31,  1.5489e+32,  1.7531e-38,  0.0000e+00],
         [ 0.0000e+00,  8.4078e-44,  0.0000e+00,  2.8026e-45,  0.0000e+00],
         [ 1.7753e+28,  1.2181e+33,  3.3328e+35,  2.1019e-43,  0.0000e+00],
         [ 0.0000e+00,  8.4078e-44,  0.0000e+00,  3.5230e+19,  4.5559e-41]],

        [[-9.8160e-30,  3.0156e-42,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00,  5.6052e-45,  0.0000e+00, -8.9196e-28,  7.5390e-43],
         [ 1.4956e+14,  1.5984e+03,  0.0000e+00,  0.0000e+00,  2.1019e-44],
         [ 0.0000e+00,  2.6968e+23,  3.3259e+22, -1.2659e-29,  7.5390e-43]]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x_6_10 = x.view(6,10)
x_res_6_6 = torch.matmul(x_6_10, x_6_10.t())
x_res_6_6.size()

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.autograd.Variable(torch.FloatTensor([1.0]), requires_grad = True)
z = torch.autograd.Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = torch.autograd.Variable(torch.FloatTensor([2.0]), requires_grad = True)
y= x**3 + z + 75*t
y.backward()

print(f'x={x.grad}')
print(f'z={z.grad}')
print(f't={t.grad}')

x=tensor([3.])
z=tensor([1.])
t=tensor([75.])


In [8]:
# Создайте единичный тензор размера 5x6
x2 = torch.ones(5,6)
x2

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
x2.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [10]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
w1 = torch.autograd.Variable(torch.Tensor([0.1,0.2]), requires_grad = True)
optimizer = torch.optim.SGD([w1], lr=0.01)
criterion = torch.nn.MSELoss()
x = torch.autograd.Variable(torch.Tensor([1.0,2.0]), requires_grad = False)
y = torch.autograd.Variable(torch.Tensor([1.0,2.0]), requires_grad = False)
y_func = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
pred = y_func
loss = criterion(pred, y)
loss.backward()     # считаем градиент для w1
optimizer.step()    # обновляем веса w1

print(f'loss:\t {loss.item()}')
print(f'w1:\t {w1.data}')

loss:	 11.916261672973633
w1:	 tensor([0.1000, 0.2307])
